name: aip_proj_cpu
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.4
  - matplotlib
  - numpy
  - scikit-image
  - pytorch=1.12.1
  - pytorch-mutex=1.0=cpu
  - torchvision=0.13.1
  - cpuonly
