#----------------------------------------------------------------------------
# Created By  : Sayak Mukherjee
# Created Date: 02-Nov-2022
# version ='1.0'
# ---------------------------------------------------------------------------
# This file contains methods to apply post-processing to the inpainted 
# samples generated by the context-encoder. This is an extension and not
# implemented in the original paper.
# ---------------------------------------------------------------------------